### PR TITLE
fix(engine-core): change console.errors to console.warns(#3692)

### PR DESCRIPTION
**Pull request by yashpatel1998**
## Details

change console.errors to console.warns
*fix: display warning instead of errors if the rendering continues despite the absence of lwc:dom="manual" directive

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

### CODE REVIEW

**Comment by abdulsattar** [comment]
@yashpatel1998 what's the motivation for this? `console.error` doesn't block rendering and will continue.

**Comment by yashpatel1998** [comment]
I have already accepted the CLA but seems it is not reflected here
image

**Comment by jmsjtu** [comment]
@yashpatel1998 could you confirm that the email used to sign your commits is the same as the one listed on your GitHub account (yashpatel.dev@gmail.com)?

**Comment by yashpatel1998** [comment]
@jmsjtu I confirm it is the same email address. Will re-running the bot pipeline fix the issue by any chance?

**Comment by nolanlawson** [comment]
@yashpatel1998 You could try pushing a new commit to this branch?

**Comment by nolanlawson** [comment]
BTW this will almost certainly have some broken tests once the CI runs... if you do `cd packages/@lwc/integration-karma && yarn test`, you will see the test failures.

**Comment by yashpatel1998** [comment]
@nolanlawson Pushed the integration-karma test changes. Could you check if the changes look good now? 
A side note, the tests were failing for me in development mode with below error but succeeded for production. Not sure if this is intended. 
image

**Comment by nolanlawson** [comment]
@yashpatel1998 If the tests are failing in development mode, it looks like it's because there is a console.warn/error that is not being accounted for. The test are designed such that, if you forget to add the correct `expect().toLog*Dev` wrapper, then it will fail the tests overall.

Thank you again for the PR!

**Comment by yashpatel1998** [comment]
@nolanlawson Got you. Let me look into it and push the fix. Thank you for the help ! :)

**Comment by yashpatel1998** [comment]
@nolanlawson Lastest commit should fix the failing tests. Let me know if there are changes to be done.

**Review by nolanlawson — APPROVED** [review]
LGTM. +1 when the CI tests are passing.

Thank you @yashpatel1998 !! 🎉

**Comment by nolanlawson** [comment]
This doesn't fully resolve #3692 but it does fix probably the biggest source of spurious console errors.

**Comment by yashpatel1998** [comment]
@nolanlawson Do you want me to replace other console.errors as part of the same issue later? 

Excited for my first successful contribution to the framework! 😁

**Comment by nolanlawson** [comment]
@yashpatel1998 Sure, those can be done in a separate PR. :) Thanks again for the contribution!

**Comment by nolanlawson** [comment]
Integration tests are failing but they look unrelated to this PR. Might need to check if something changed in Chrome or something.

**Comment by yashpatel1998** [comment]
Yeah, seems like. 
Sure. I will take a look at the new PR,

**Comment by nolanlawson** [comment]
Thanks very much!

**Pull request merged**
