### PR TITLE
fix(template-compiler): add deprecated void elements back (#3037) @W-11731797

### PR DESCRIPTION
**Pull request by jmsjtu**
## Details
Backport of #3037 for 240.

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ⚠️ Yes, it does include an observable change.

See #3037 

## GUS work item
W-11731797

### CODE REVIEW

**Review by ravijayaramappa — APPROVED** [review]

**Review by ravijayaramappa — APPROVED** [review]

**Comment by jmsjtu** [comment]
/nucleus ignore --reason "lwc-platform is building from master and not winter23"

**Comment by ravijayaramappa** [comment]
/nucleus ignore -m "lwc-platform is building from master and not winter23"

**Pull request merged**
