### PR TITLE
feat: adding missing aria attributes

### PR DESCRIPTION
**Pull request by MamataLV**
## Details
Github issue link: https://github.com/salesforce/lwc/issues/3693
This PR is to add missing ARIA attributes:
1. ariaColIndexText
2. ariaRowIndexText
3. ariaDescription
4. ariaBrailleLabel
5. ariaBrailleRoleDescription

Followed Resources: https://w3c.github.io/aria/#ARIAMixin , https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-braillelabel, And already existing similar ARIA attributes.

## Does this pull request introduce a breaking change? 

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ⚠️ Yes, it does include an observable change.

The observable changes are only related to ARIA, hence improving accessibility.

### CODE REVIEW

**Comment by jmsjtu** [comment]
Thanks for opening this PR @MamataLV, before moving forward could you sign the CLA?

Once it's signed, the CI will run through all our tests.

**Comment by MamataLV** [comment]
> Thanks for opening this PR @MamataLV! Before moving forward could you sign the CLA?
> 
> Once it's signed, the CI will run through all our tests.

Hi @jmsjtu
When click on it it says "You already signed the CLA on 2023-09-12", but it was not successful, any alternative way to sign CLA?

**Comment by nolanlawson** [comment]
This looks great, thank you! A few suggestions:

1. We should wait until #3666 is merged – we do not want to add anything to the global polyfill
2. I think `aria-description` is obviously a good addition since it's _both_ in Chrome and in the spec, but some of them are spec-only or Chrome-only. At the very least, we should research if there are any potential problems with those attributes, and probably file a bug on Chrome and/or on the spec to make them consistent.

**Comment by nolanlawson** [comment]
Also, I believe you will need to push a new commit to this branch, so that the CLA bot will be happy.

**Comment by nolanlawson** [comment]
Looking into [Firefox's upcoming support](https://github.com/salesforce/lwc/issues/3693#issuecomment-1721527220), I think `ariaColIndexText` and `ariaRowIndexText` are safe to add. Both of them are both 1) in the spec and 2) in Firefox.

For any reflection that is in the spec and in at least one browser, I think it's safe for us to support.

For `ariaBrailleLabel` and `ariaBrailleRoleDescription`, I have filed a PR on the spec: https://github.com/w3c/aria/pull/2039

**Comment by MamataLV** [comment]
> Thanks for opening this PR @MamataLV! Before moving forward could you sign the CLA?
> 
> Once it's signed, the CI will run through all our tests.

CLA signed

**Comment by nolanlawson** [comment]
Thanks @MamataLV! Sorry for the delay, but we are still working on merging https://github.com/salesforce/lwc/pull/3666

**Comment by nolanlawson** [comment]
@MamataLV You have some test failures in the Karma tests, could you please run `yarn && cd packages/@lwc/integration-karma && yarn test` and take a look? There is a README in `@lwc/integration-karma` that also explains how to debug. Thank you!

**Comment by nolanlawson** [comment]
Sorry for the silence, but given that https://github.com/w3c/aria/pull/2039 is approved, I think we are good to ship all 5 new ARIA reflections.

The one thing we are waiting on now is #3666 which I hope to ship in a week or two.

**Comment by nolanlawson** [comment]
Sorry that our CI tests cannot run from forks @MamataLV. I checked, and it looks like you are getting test failures. You can repro using `yarn && cd packages/@lwc/integration-karma && yarn start` and then clicking "debug."

It looks like what's happening is that the new attributes, such as `aria-braillelabel`, are being treated like IDref attributes such as `aria-labelledby` and are being transformed in synthetic shadow (when they should not be).

**Comment by nolanlawson** [comment]
OK, it turns out it was just a test issue. Fixed the tests ^

**Review by nolanlawson — APPROVED** [review]

**Pull request merged**
