### PR TITLE
feat: use fragments for slots in light DOM (BREAKING CHANGE)

### PR DESCRIPTION
**Pull request by abdulsattar**
## Details
We used to flatten slotted content in light DOM. In this PR, we replace that with fragments.

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ⚠️ Yes, it does include an observable change.
`childNodes` returns two extra text nodes.

### CODE REVIEW

**Comment by nolanlawson** [comment]
This looks like a great change, but due to the observable change (to `childNodes`) and the snapshot breakages, I'm guessing we will need to put this behind a compiler flag?

**Comment by nolanlawson** [comment]
@abdulsattar At this point, should we deploy this feature using API versioning? It should be safe to merge that way, after the API versioning PRs are merged.

The only change would be that the compiler would have to emit different vnodes based on the API version, and the engine would have to be capable of consuming both.

**Review by jye-sf — COMMENTED** [review]
As expected, downstream snapshots are failing from the extra text nodes.

One unusual thing though: some of those TFs are failing with only 1 additional newline, for example:
```
    <div class="__lwc_scope_token__ column-content">
+     ‍‍
    </div>
  </community_layout-column>

```
Is that expected?

**Comment by nolanlawson** [comment]
closing in favor of https://github.com/salesforce/lwc/pull/3649

**Pull request closed without merging**
