### PR TITLE
chore: release v2.23.6

### PR DESCRIPTION
**Pull request by jmsjtu**
## Details
Weekly release v2.23.6

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ⚠️ Yes, it does include an observable change.

See #2977

## GUS work item
W-11466097

### CODE REVIEW

**Review by ravijayaramappa — APPROVED** [review]

**Comment by jmsjtu** [comment]
Proceeding with this release, because of a bug in nucleus the `ui-interaction-builder-components` downstream dependency is unable to complete building.  

Will ignore nucleus tests for now.

**Pull request merged**
