### PR TITLE
chore(engine-server): run test fixtures concurrently

### PR DESCRIPTION
**Pull request by cardoso**
## Details

Small but easy improvement observed locally ~1.65s to ~1.25s.

This is still the longest-running test file (in subsequent runs), so this might help uncover other ways to improve.

## Does this pull request introduce a breaking change?

-   😮‍💨 No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

-   🤞 No, it does not introduce an observable change.

### CODE REVIEW

**Review by wjhsf — APPROVED** [review]
Pretty cool! Is there any perf gain if we do this for fixtures in other packages as well?

**Comment by cardoso** [comment]
@wjhsf yes, I have another PR coming up which refactors the test-fixture-dir.ts file and removes the custom `toMatchFile` sync matcher in favor of vitest's async `toMatchFileSnapshot`. I saw bigger improvements (~1s for this test), but wanted to push this simple one first to see the difference. It also improves the UX when using vitest through VSCode:

Screenshot 2024-10-24 at 11 31 01

With the custom matcher it won't show the diff and file locations as nicely:

Screenshot 2024-10-24 at 11 33 07

**Review by nolanlawson — APPROVED** [review]
Awesome!

**Pull request merged**
