### PR TITLE
Blittle moretests

### PR DESCRIPTION
**Pull request by blittle**
## Details
Add more tests

## Does this PR introduce breaking changes?
* ✅ `No, it does not introduce breaking changes.`

If yes, please describe the impact and migration path for existing applications.

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? ✅ 
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅

### CODE REVIEW

**Comment by diervo** [comment]
Merged this already

**Comment by blittle** [comment]
@diervo there were a few more tests in here

**Comment by blittle** [comment]
@diervo you merged right before I pushed a few more.

**Comment by diervo** [comment]
@blittle sorry feel free to add them to the final branch, I had to remerge again from usptream

**Pull request closed without merging**
