### PR TITLE
chore: release v2.31.0 @W-11466097

### PR DESCRIPTION
**Pull request by ravijayaramappa**
## Details
For nucleus to release v2.31.0

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

### CODE REVIEW

**Review by jmsjtu — APPROVED** [review]

**Comment by jmsjtu** [comment]
/nucleus ignore -m "downstream is failing because of a nexus connection issue"

**Comment by ravijayaramappa** [comment]
/nucleus ignore -m 'nrkruk/lwc-dev-core is failing in setup process

**Pull request merged**
