### PR TITLE
chore(deps): update prettier to v3

### LINKED ISSUE #4386: Upgrade to prettier v3
Jest currently does not play well with ESM packages. Prettier v3 is a purely ESM package. We use prettier in our jest tests.
https://github.com/salesforce/lwc/blob/173391624170b8fa3e5c9b7f53521e5d13c47ab1/packages/%40lwc/template-compiler/src/__tests__/fixtures.spec.ts#L10
If jest adds better ESM support, if we drop jest (#4153), or if we change that test file, then we will be able to upgrade to prettier v3.

Note that we can run `NODE_OPTIONS=--experimental-vm-modules yarn test` to fix the error when importing prettier, but that causes a different error when jest internals try to import `@parse5/tools`.

See #4384 and #4140 for prior attempts to do this.

### PR DESCRIPTION
**Pull request by cardoso**
## Details

Some snapshots had to be updated. See: https://github.com/prettier/prettier/pull/9559 https://github.com/prettier/prettier/issues/15835

Removed @types/prettier dependency (deprecated) as prettier v3 provides its own type definitions.

Closes #4386

## Does this pull request introduce a breaking change?

-   😮‍💨 No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

-   🤞 No, it does not introduce an observable change.

### CODE REVIEW

**Review by wjhsf — APPROVED** [review]
Gotta run prettier on the code base. 🫠 Please update the prettierrc to minimize the diff, if there's any config that can be updated.

Also, just for the GitHub auto magic, this closes #4386, not #4384.

**Review by nolanlawson — APPROVED** [review]

**Comment by nolanlawson** [comment]
Thanks a bunch! 🎉

**Pull request merged**
