### PR TITLE
chore: Remove outdated documents and unused code

### PR DESCRIPTION
**Pull request by pmdartus**
## Details

- Remove outdated `docs/` folder
- Remove unused `CHANGELOG.md`
- Remove unused jest helpers in `@lwc/engine-core`

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? ✅ 
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅

### CODE REVIEW

**Review by ekashida — COMMENTED** [review]
I think some of the content in `restrictions.md` is valuable because it reasons about certain LWC design decisions. Maybe we can preserve that information by moving it into comments in the source?

**Review by nolanlawson — APPROVED** [review]

**Comment by pmdartus** [comment]
I moved the `restriction.md` content to [quip doc](https://salesforce.quip.com/htzcAek59xDd) as there is a lot to unpack in here. Some of the restrictions proposed in the document only apply to synthetic shadow DOM and will probably never be implemented.

**Review by jodarove — COMMENTED** [review]
Should we update the [wire-service/readme.md](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/wire-service/README.md) so it states that the package is deprecated?

**Comment by pmdartus** [comment]
> Should we update the wire-service/readme.md so it states that the package is deprecated?

Let's do this in a separate PR.

**Review by jodarove — APPROVED** [review]

**Review by ekashida — APPROVED** [review]

**Pull request merged**
