### PR TITLE
chore: v3.1.1

### PR DESCRIPTION
**Pull request by jye-sf**
## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

### CODE REVIEW

**Comment by jye-sf** [comment]
Mainly contains dependency updates.

**Comment by nolanlawson** [comment]
Why is this a minor version bump instead of a patch version bump?

**Comment by jye-sf** [comment]
I bumped the minor version because some of the dependency updates were minor version updates, but yeah I can switch this over to be a patch version bump instead.

**Comment by nolanlawson** [comment]
Yeah I think from our consumer's POV, our own deps' minor version bumps don't constitute a minor version bump for us.

**Review by nolanlawson — APPROVED** [review]

**Pull request merged**
