### PR TITLE
refactor(engine): remove locator infrastructure

### PR DESCRIPTION
**Pull request by caridy**
## Details

Removing this platform specific feature from the engine, hoping that we can create something more compelling in the near future.

* removal of all the service pieces for locator
* removal of compiler locator parts
* removal of locator unit tests in engine

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

## GUS workitem
W-6741594

### CODE REVIEW

**Comment by tariqrafique** [comment]
This commit has everything added for locators https://github.com/salesforce/lwc/commit/464daf4c5d91009adba7c550900aa1cb98dcf089

**Comment by tariqrafique** [comment]
We will also need to remove the perforce part that registers with the engine for locator hooks

https://swarm.soma.salesforce.com/files/app/main/core/ui-instrumentation-components/modules/instrumentation/locatorService/locatorService.js
just need to remove the engine.register call

**Comment by tariqrafique** [comment]
oh and this commit has the error messages that need to be removed: https://github.com/salesforce/lwc/commit/a212efd6bb521d98fbadf9e3694f6069ee2f1635

**Comment by caridy** [comment]
@jodarove @apapko @ravijayaramappa can you work with @tariqrafique to get this removed?

**Comment by diervo** [comment]
Last time I checked, nobody is using them

**Comment by caridy** [comment]
yes @diervo that's clear at this point, the rest is just clean up.

**Comment by jodarove** [comment]
thanks for pointing to the exact commits @tariqrafique! @pmdartus this pr is ready for another pass.

**Comment by caridy** [comment]
LGTM @jodarove

**Comment by tariqrafique** [comment]
@jodarove don't forget to remove this bit as well: https://swarm.soma.salesforce.com/files/app/main/core/ui-instrumentation-components/modules/instrumentation/locatorService/locatorService.js#L17

**Comment by jodarove** [comment]
yep, is here 21426509. thank you!

**Pull request merged**
