### PR TITLE
docs(@lwc/wire-service): add a setup section

### PR DESCRIPTION
**Pull request by blittle**
Add an example of how to register the wire service with LWC

## Details
This took me a while to discover, and I feel like it would be worthwhile in the documentation.

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

If yes, please describe the impact and migration path for existing applications.

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? N/A
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅

### CODE REVIEW

**Comment by diervo** [comment]
@kevinv11n @caridy do we want to expose this API or shall we wait?

**Comment by blittle** [comment]
@diervo does the wire adapter work at all if it isn't registered? I have a project based upon `create-lwc-app` and couldn't get the wire adapter to work at all until I did this.

**Comment by diervo** [comment]
Not today, but we have changed a lot of things so you don't need to do that anymore. Thats why Im asking Caridy and Kevin who know more about the latests.

**Comment by priandsf** [comment]
@diervo I have a blog post almost ready on this API. It features a disclaimer stating that it is not officially supported, will change (at least for the developers), and is for LWC OSS. I created a quick sample here to illustrate the principles: https://developer.salesforce.com/docs/component-library/tools/playground/8peP8wto/6/edit

**Comment by caridy** [comment]
> @kevinv11n @caridy do we want to publicly document this API or shall we wait?

No, this API will be effectively legacy as soon as @jodarove merges the wire reform in the upcoming hours/days.

In fact, in platform, those are already quite restrictive.

Instead, let's make sure that @jodarove adds a section about the wire adapters API based on the RFC.

**Comment by diervo** [comment]
Bret, hopefully we can reuse the work you have done on the new APIs.
Hopefully this won’t discourage you to contribute more :)

**Comment by blittle** [comment]
@diervo no, no problem at all! I'm new here, and I'm trying to navigate the various flavors of LWC in addition to what's coming next.

**Pull request closed without merging**
