### PR TITLE
chore(ci): parallelize karma tests

### LINKED ISSUE #3822: Run Karma tests in CI in parallel
The Karma tests take ~21 minutes to run, and this will get slower by 2 minutes every release (due to API versioning adding two new tests, one for synthetic and one for native shadow).

This will not be easy to parallelize since we gather code coverage information at the very end. However, it should still be possible to merge all the code coverage reports together.

Alternatively, we can get rid of the code coverage tests, since we still are not reporting it in a very visible way: #3467. But it would be nice to both parallelize and have visible code coverage reports.

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #3822 

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

### CODE REVIEW

**Comment by nolanlawson** [comment]
The runtime has improved from ~25 minutes to ~16 minutes. Unfortunately there are limits on further parallelizing:

- Coverage results must be uploaded/downloaded between jobs. Each upload takes ~20s, each download takes ~1min.
- We don't have NX caching in place (#3841) so we pay a ~1min cost to run `yarn build` on each job
- GitHub Actions doesn't have [great ways to share code](https://stackoverflow.com/a/71570780), so each extra job adds a lot of boilerplate.

I still think 16 minutes is a big improvement over 25 minutes, but this can be improved further in the future.

**Comment by nolanlawson** [comment]
Summary:

Screenshot 2023-10-31 at 12 55 31 PM

**Comment by nolanlawson** [comment]
Coverage numbers are the same before and after.

Coverage report in this PR:

```
$ node ./scripts/merge-coverage.js
-------------------|---------|----------|---------|---------|-------------------
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------|---------|----------|---------|---------|-------------------
All files          |   89.34 |    83.43 |   88.38 |   89.27 |                   
 engine-dom/dist   |   92.44 |    87.17 |   91.07 |   92.36 |                   
  index.js         |   92.44 |    87.17 |   91.07 |   92.36 | ...8383-8414,8583 
 ...ic-shadow/dist |    82.4 |    75.19 |   83.23 |    82.2 |                   
  index.js         |    82.4 |    75.19 |   83.23 |    82.2 | ...4164,4229,4260 
 wire-service/dist |    75.3 |    63.88 |   81.81 |   75.32 |                   
  index.js         |    75.3 |    63.88 |   81.81 |   75.32 | ...27,[13](https://github.com/salesforce/lwc/actions/runs/6711453409/job/18239211089?pr=3840#step:7:14)2-[15](https://github.com/salesforce/lwc/actions/runs/6711453409/job/18239211089?pr=3840#step:7:16)0,[16](https://github.com/salesforce/lwc/actions/runs/6711453409/job/18239211089?pr=3840#step:7:17)3 
-------------------|---------|----------|---------|---------|-------------------
```

Coverage report in `master`:

```
$ node ./scripts/merge-coverage.js
-------------------|---------|----------|---------|---------|-------------------
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------|---------|----------|---------|---------|-------------------
All files          |   89.34 |    83.43 |   88.38 |   89.27 |                   
 engine-dom/dist   |   92.44 |    87.17 |   91.07 |   92.36 |                   
  index.js         |   92.44 |    87.17 |   91.07 |   92.36 | ...8383-8414,8583 
 ...ic-shadow/dist |    82.4 |    75.19 |   83.23 |    82.2 |                   
  index.js         |    82.4 |    75.19 |   83.23 |    82.2 | ...4164,4229,4260 
 wire-service/dist |    75.3 |    63.88 |   81.81 |   75.32 |                   
  index.js         |    75.3 |    63.88 |   81.81 |   75.32 | ...27,[13](https://github.com/salesforce/lwc/actions/runs/6710461259/job/18235691983#step:24:14)2-150,163 
-------------------|---------|----------|---------|---------|-------------------
Done in 1.62s.
```

**Review by ekashida — APPROVED** [review]
lgtm!

**Pull request merged**
