### PR TITLE
fix(synthetic-shadow): fix light DOM serialization

### LINKED ISSUE #2425: Light DOM serialization is incorrect when mixed with synthetic shadow DOM
### Description

The following API report incorrect values when mixing light DOM with synthetic shadow DOM:
- `Node.prototype.textContent`
- `Element.prototype.innerHTML`
- `Element.prototype.outerHTML`

Failing test examples added via #2393

### Browsers Affected
All

### Version
- LWC: 2.2.8

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Related: #2502 #2540

This reverts commit 0de7ef2685fd26f0ba7d56987c8562a880922fe8.

Fixes #2425

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ⚠️ Yes, it does include an observable change.

The observable changes have been described elsewhere.

## GUS work item

W-10059718

### CODE REVIEW

**Comment by nolanlawson** [comment]
Note that this change will have a big impact, so we'll want to be strategic with when we merge out, how we announce it, etc.

**Review by ekashida — APPROVED** [review]

**Comment by nolanlawson** [comment]
Downstream test in `ui-dxp-components` failing due to a snapshot test; the snapshot now has `#shadow-root` when it didn't before.

**Comment by nolanlawson** [comment]
/nucleus ignore --reason "Downstream test uses a snapshot that has changed"

**Comment by nolanlawson** [comment]
This is ready to merge, but I'm holding off until next week to avoid bundling it with the other synthetic shadow change (#2547).

**Comment by nolanlawson** [comment]
/nucleus ignore --message "Expected downstream snapshot test failure"

**Comment by nolanlawson** [comment]
/nucleus ignore --reason "Expected downstream snapshot test failure"

**Comment by nolanlawson** [comment]
The snapshot changes seem directly related to this PR. AFAICT it's not a true breakage but just that the snapshot is correct now when it wasn't before (just showed `<slot>`).

**Pull request merged**
