### PR TITLE
build: resolve @best version discrepancy in yarn.lock

### PR DESCRIPTION
**Pull request by ekashida**
## Details

package.json uses `beta5` but yarn.lock specifies `beta4`

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

### CODE REVIEW

**Comment by pmdartus** [comment]
@ekashida How did you realized that? The CI should have failed because of the `--frozen-lockfile` flag passed to the install.

**Comment by ekashida** [comment]
@pmdartus I didn't do anything out of the ordinary--I pulled the latest, installed, and git wouldn't let me create a new branch without stashing because of these changes.

**Comment by pmdartus** [comment]
Ok good to know. Yarn might only check root level packages.

**Comment by diervo** [comment]
Yeah this is indeed very weird

**Pull request merged**
