### PR TITLE
build: enable integration tests for forked repos

### PR DESCRIPTION
**Pull request by Sumitjg**
## Details
Enabling integration test for forked repos using context to avoid exposing sauce lab secrets.

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.

If yes, please describe the impact and migration path for existing applications.

## The PR fulfills these requirements:
* Have tests for the proposed changes been added?  ❌
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅

## GUS work item
W-8434068

### CODE REVIEW

**Comment by pmdartus** [comment]
Reading the context CircleCI documentation. Any job using the newly introduced context should fail `Unauthorized` if the person who triggers it is not part of the Salesforce GitHub org. IMO, this partially solves the original issue which is to enable external contributors to create PR on the repository.

For this to work, we would need to add a new [approval step](https://circleci.com/docs/2.0/contexts/#approving-jobs-that-use-restricted-contexts) to the workflow.

**Comment by Sumitjg** [comment]
@pmdartus is it okay to have manual approval step for both forked as well as for non-forked repos ? I will try to add manual approval step only for forked repo but if not able to then it will be there for both.

**Comment by pmdartus** [comment]
> is it okay to have manual approval step for both forked as well as for non-forked repos ?

This is a show stopper for me. I don't think we want to be in the business of babysitting our CI.

**Comment by Sumitjg** [comment]
Yes, I agree. Trying to have separate workflows for both use-cases.

**Comment by Sumitjg** [comment]
@pmdartus updated PR. SO now there will be two different workflows,one each for forked and non-forked repos. Please review.

**Comment by Sumitjg** [comment]
https://github.com/salesforce/lwc/pull/2186 and https://github.com/salesforce/lwc/pull/2187 are the sample PRs for forked and non-forked repos with this code changes.

**Review by pmdartus — APPROVED** [review]
Looks good to me.

**Review by ravijayaramappa — APPROVED** [review]

**Review by ekashida — APPROVED** [review]

**Pull request merged**
