### PR TITLE
renderComponentToStaticMarkup() for Server Side Rendering with syntheticShadowDom

### PR DESCRIPTION
**Pull request by KrisGraySFDC**
## Details
Just as [ReactDomServer](https://reactjs.org/docs/react-dom-server.html#rendertostaticmarkup) has `renderToStaticMarkup()` so too should @lwc/engine-server

This PR adds that method in, it also specifies to use synthetic shadow which will be useful for writing encapsulated CSS from the server.

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

If yes, please describe the impact and migration path for existing applications.

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? ❌ - Not Yet, waiting for verification on approach.
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅

### CODE REVIEW

**Comment by KrisGraySFDC** [comment]
Needs a: RFC label

**Comment by KrisGraySFDC** [comment]
@pmdartus and @diervo I could use this in the OpenDocs Framework and so I thought I'd officially send this PR. 

No tests yet, but if we liked it, I could get it production ready 
 - Reduce Duplication
 - Tests
 - Doc

**Comment by diervo** [comment]
I like the idea, I know @pmdartus will have lots of opinions :)

**Comment by pmdartus** [comment]
@KrisGraySFDC thanks for taking the time to open this PR. However, this looks like a duplicate of https://github.com/salesforce/lwc/pull/2093. 

I will close this PR for now so we can focus on the original one.

**Comment by KrisGraySFDC** [comment]
@pmdartus thanks! Didn't notice Phillippe already beat me too it.

**Pull request closed without merging**
