### PR TITLE
chore: update to rollup 2.7.3

### PR DESCRIPTION
**Pull request by jodarove**
## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

### CODE REVIEW

**Comment by jodarove** [comment]
rollup is not tree-shaking some assertions, especially those that are done within `runWithBoundaryProtection`, example:

```js
  function invokeEventListener(vm, fn, thisValue, event) {
    const {
      callHook,
      owner
    } = vm;
    runWithBoundaryProtection(vm, owner, noop$3, () => {
      // job
      if ("production" !== 'production') {
        assert.isTrue(isFunction(fn), `Invalid event handler for event '${event.type}' on ${vm}.`);
      }

      callHook(thisValue, fn, [event]);
    }, noop$3);
  }
```

**Comment by diervo** [comment]
If we update rollup to 2.x we have to update it everywhere, which will be harder thatn we thoguht.

**Comment by jodarove** [comment]
mmm, interesting, the current rollup `1.32.1` generates the same output.

**Comment by pmdartus** [comment]
@diervo What do you mean that we have to update everywhere? This change looks fine to me.

**Pull request merged**
