### PR TITLE
test(integration-karma): avoid testing with production artifacts

### PR DESCRIPTION
**Pull request by ekashida**
## Details

Avoid testing with production artifacts. This will allow us to test features that are behind feature flags.

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

### CODE REVIEW

**Comment by pmdartus** [comment]
I have been thinking about this, I recall now why we added the production test. It was because we had a different behavior in DEV and PROD, so running the same test suite on the CI allowed to catch such issues.

Instead of disabling the PROD tests, I would like if we can come up with a strategy to switch the flags even in PROD for those tests.

**Comment by caridy** [comment]
I believe those observable differences are mostly about asserts vs no asserts in place... which produces different error type. Eventually, I will like that to be resolved... I have some ideas, but other than that... it should be ok. I think we can do this now, and work on the similarities in another PR.

**Comment by ekashida** [comment]
@diervo @pmdartus and I discussed this in person and concluded that the prod tests were worth keeping because we could restrict usage `setFeatureFlag` in core (via whitelist or lint rule), but after discussing further with @caridy we realized that, due to tree-shaking, we can't test features in prod unless it is behind a dynamic feature flag.

**Comment by caridy** [comment]
My proposal is:

* merge this... remove the tests from prod
* lets work on another PR to clean up the tests (which is pending work anyways), add the error codes, and make sure that those errors are the same in prod/dev

**Pull request merged**
