### PR TITLE
chore: enable Nucleus for all PRs

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Enables Nucleus for all PRs.

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

## GUS work item

W-10179854

### CODE REVIEW

**Comment by tdalbo92** [comment]
Just fixed the failure in `lds/lds-container-test`, it should pass when this is rerun.

**Comment by nolanlawson** [comment]
OK, so apparently we will not see the impact of `required-downstream-deps` until this is merged into master. So we should probably start with a small, conservative subset and work our way up from there.

**Comment by nolanlawson** [comment]
I've whittled it down to `lwc-platform`, `luvio`, and `lwr`. There are other projects that are green, but let's start with something small for now since we may have to deal with flakiness.

**Review by ekashida — APPROVED** [review]
Nit: I would prefer not to have the commented list of existing downstream projects.

**Comment by nolanlawson** [comment]
Sure, I can remove the comments. I just figured it would make it easier in the future to uncomment stuff, but we can definitely type them out instead. YAGNI

**Review by pmdartus — APPROVED** [review]

**Comment by tdalbo92** [comment]
@nolanlawson My request would be to also have `lds-lightning-platform` in that list too.

**Comment by nolanlawson** [comment]
@tdalbo92 We will add a lot more to the list later; we're just being really cautious at first. 🙂

**Pull request merged**
