### PR TITLE
chore: release v2.30.0

### PR DESCRIPTION
**Pull request by nolanlawson**
## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

### CODE REVIEW

**Comment by nolanlawson** [comment]
/nucleus ignore --reason "ui-commerce-components failing due to ~99.9% rather than 100% code coverage"

**Review by ravijayaramappa — APPROVED** [review]

**Comment by ravijayaramappa** [comment]
/nucleus ignore --reason "ui-commerce-components failing due to ~99.9% rather than 100% code coverage"

**Comment by ravijayaramappa** [comment]
/nucleus ignore --force --reason "ui-commerce-components failing due to ~99.9% rather than 100% code coverage"

**Pull request merged**
