### PR TITLE
release: bump version to v2.13.1

### PR DESCRIPTION
**Pull request by rui-rayqiu**
## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

### CODE REVIEW

**Review by ravijayaramappa — APPROVED** [review]

**Comment by rui-rayqiu** [comment]
/nucleus ignore --reason "a downstream project salesforcedevs/developer-website has build issues that seem not to relate to lwc"

**Comment by rui-rayqiu** [comment]
/nucleus ignore --reason "a downstream project salesforcedevs/developer-website has build issues that seem not to relate to lwc"

**Pull request merged**
